package io.github.rajeev02.imgurlib.models.common


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

@JsonClass(generateAdapter = true)
data class Image(
    @Json(name = "account_id")
    val accountId: Any? = Any(),
    @Json(name = "account_url")
    val accountUrl: Any? = Any(),
    @Json(name = "ad_type")
    val adType: Int? = 0,
    @Json(name = "ad_url")
    val adUrl: String? = "",
    @Json(name = "animated")
    val animated: Boolean? = false,
    @Json(name = "bandwidth")
    val bandwidth: Long? = 0,
    @Json(name = "comment_count")
    val commentCount: Any? = Any(),
    @Json(name = "datetime")
    val datetime: Int? = 0,
    @Json(name = "description")
    val description: String? = "",
    @Json(name = "downs")
    val downs: Any? = Any(),
    @Json(name = "edited")
    val edited: String? = "",
    @Json(name = "favorite")
    val favorite: Boolean? = false,
    @Json(name = "favorite_count")
    val favoriteCount: Any? = Any(),
    @Json(name = "gifv")
    val gifv: String? = "",
    @Json(name = "has_sound")
    val hasSound: Boolean? = false,
    @Json(name = "height")
    val height: Int? = 0,
    @Json(name = "hls")
    val hls: String? = "",
    @Json(name = "id")
    val id: String? = "",
    @Json(name = "in_gallery")
    val inGallery: Boolean? = false,
    @Json(name = "in_most_viral")
    val inMostViral: Boolean? = false,
    @Json(name = "is_ad")
    val isAd: Boolean? = false,
    @Json(name = "link")
    val link: String? = "",
    @Json(name = "mp4")
    val mp4: String? = "",
    @Json(name = "mp4_size")
    val mp4Size: Int? = 0,
    @Json(name = "nsfw")
    val nsfw: Any? = Any(),
    @Json(name = "points")
    val points: Any? = Any(),
    @Json(name = "processing")
    val processing: Processing? = Processing(),
    @Json(name = "score")
    val score: Any? = Any(),
    @Json(name = "section")
    val section: Any? = Any(),
    @Json(name = "size")
    val size: Int? = 0,
    @Json(name = "tags")
    val tags: List<Tag>? = listOf(),
    @Json(name = "title")
    val title: Any? = Any(),
    @Json(name = "type")
    val type: String? = "",
    @Json(name = "ups")
    val ups: Any? = Any(),
    @Json(name = "views")
    val views: Int? = 0,
    @Json(name = "vote")
    val vote: Any? = Any(),
    @Json(name = "width")
    val width: Int? = 0,
    @Json(name = "ad_config")
    val adConfig: AdConfig? = AdConfig(),
    @Json(name = "cover")
    val cover: String? = "",
    @Json(name = "cover_height")
    val coverHeight: Int? = 0,
    @Json(name = "cover_width")
    val coverWidth: Int? = 0,
    val images: List<Image>? = listOf(),
    @Json(name = "images_count")
    val imagesCount: Int? = 0,
    @Json(name = "include_album_ads")
    val includeAlbumAds: Boolean? = false,
    @Json(name = "is_album")
    val isAlbum: Boolean? = false,
    @Json(name = "layout")
    val layout: String? = "",
    @Json(name = "privacy")
    val privacy: String? = "",
    @Json(name = "topic")
    val topic: Any? = Any(),
    @Json(name = "topic_id")
    val topicId: Int? = 0,
)